export const moduleFirst = {
    state: () => ({
        tooth18: {
            stage1: {
                stageNumber: '1',
                toothNumber: '18',
                typeConstruction: "-",
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isRemoteTooth: false, //Подумать насчет изменений значений не стейте а прокидывать настоящим инжектом
                isHealthyTooth: false,
                isDefaultStyle: true,
                isFilledTooth: false, //Изменить на тру, при изменении стейта, дает заполненным зубам на карте фиолетовую окраску
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '18',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth17: {
            stage1: {
                stageNumber: '1',
                toothNumber: '17',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '17',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth16: {
            stage1: {
                stageNumber: '1',
                toothNumber: '16',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '16',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth15: {
            stage1: {
                stageNumber: '1',
                toothNumber: '15',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '15',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth14: {
            stage1: {
                stageNumber: '1',
                toothNumber: '14',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '14',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth13: {
            stage1: {
                stageNumber: '1',
                toothNumber: '13',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '13',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth12: {
            stage1: {
                stageNumber: '1',
                toothNumber: '12',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '12',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth11: {
            stage1: {
                stageNumber: '1',
                toothNumber: '11',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '11',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth21: {
            stage1: {
                stageNumber: '1',
                toothNumber: '21',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '21',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth22: {
            stage1: {
                stageNumber: '1',
                toothNumber: '22',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '22',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth23: {
            stage1: {
                stageNumber: '1',
                toothNumber: '23',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '23',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth24: {
            stage1: {
                stageNumber: '1',
                toothNumber: '24',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '24',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth25: {
            stage1: {
                stageNumber: '1',
                toothNumber: '25',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '25',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth26: {
            stage1: {
                stageNumber: '1',
                toothNumber: '26',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '26',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth27: {
            stage1: {
                stageNumber: '1',
                toothNumber: '27',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '27',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth28: {
            stage1: {
                stageNumber: '1',
                toothNumber: '28',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '28',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth48: {
            stage1: {
                stageNumber: '1',
                toothNumber: '48',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '48',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth47: {
            stage1: {
                stageNumber: '1',
                toothNumber: '47',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '47',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth46: {
            stage1: {
                stageNumber: '1',
                toothNumber: '46',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '46',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth45: {
            stage1: {
                stageNumber: '1',
                toothNumber: '45',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '45',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth44: {
            stage1: {
                stageNumber: '1',
                toothNumber: '44',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '44',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth43: {
            stage1: {
                stageNumber: '1',
                toothNumber: '43',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '43',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth42: {
            stage1: {
                stageNumber: '1',
                toothNumber: '42',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '42',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth41: {
            stage1: {
                stageNumber: '1',
                toothNumber: '41',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '41',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth31: {
            stage1: {
                stageNumber: '1',
                toothNumber: '31',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '31',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth32: {
            stage1: {
                stageNumber: '1',
                toothNumber: '32',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '32',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth33: {
            stage1: {
                stageNumber: '1',
                toothNumber: '33',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '33',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth34: {
            stage1: {
                stageNumber: '1',
                toothNumber: '34',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '34',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth35: {
            stage1: {
                stageNumber: '1',
                toothNumber: '35',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '35',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth36: {
            stage1: {
                stageNumber: '1',
                toothNumber: '36',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '36',
                typeConstruction: '',
                implantSystem: '',
                material: '',
                colorVita: '',
                gumPart: '',
                carving: '',
                indentOptions: '',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth37: {
            stage1: {
                stageNumber: '1',
                toothNumber: '37',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '37',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        tooth38: {
            stage1: {
                stageNumber: '1',
                toothNumber: '38',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '38',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
                selectDefault: 'Выберите значение',
                isFilledTooth: false,
            }
        },
        optionsTypeConstruction: {
            Type1: {
                typeNameDefault: 'Анатомическая коронка',
                option1: {
                    titleTypeName: 'Анатомическая коронка',
                    chooseTypeName: 'Полная анатомия'
                },
                option2: {
                    titleTypeName: 'Анатомическая коронка',
                    chooseTypeName: 'С вестибулярным редуцированием',
                },
            },
            Type2: {
                typeNameDefault: 'Анатомическая коронка винтовой фиксации',
                option1: {
                    titleTypeName: 'Анатомическая коронка винтовой фиксации',
                    chooseTypeName: 'Полная анатомия'
                },
                option2: {
                    titleTypeName: 'Анатомическая коронка винтовой фиксации',
                    chooseTypeName: 'С вестибулярным редуцированием',
                },
            },
            Type3: {
                typeNameDefault: 'Каркас',
                option1: 'Выбран каркас',
            },
            Type4: {
                typeNameDefault: 'Каркас под нанесение',
                option1: 'Винтовой фиксации',
                option2: 'Цементной фиксации',
            },
            Type5: {
                typeNameDefault: 'Абатмент',
                option1: 'С использованием стандартных оснований',
                option2: 'С анодированием титанового абатмента',
                option3: 'С использованием жёлтых оснований',
            },
            Type6: {
                typeNameDefault: 'Вкладка',
                option1: 'Не разборная',
                option2: 'Разборная',
            },
            Type7: {
                typeNameDefault: 'Рельсовая балка',
                option1: 'С замками',
                option2: 'Под варку (с пинами)',
                option3: 'Под циркониевый мост',
            },
            Type8: {
                typeNameDefault: 'Культя',
                option1: 'Культя',
                option2: 'Культя винтовой фиксации',
            },
            Type9: {
                typeNameDefault: 'Хирургический шаблон',
                option1: 'Выбран хирургический шаблон',
            },
            Type10: {
                typeNameDefault: 'Сплинт',
                option1: 'Декомпрессионные (разгрузочные)',
                option2: 'Релаксационные (расслабляющие)',
                option3: 'Позиционирующие',
                option4: 'Стабилизирующие',
                option5: 'Репонирующие',
                option6: 'Ретенционные',
            },
            SelectOption1: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption2: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption3: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption4: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption5: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption6: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption7: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption8: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption9: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption10: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
        }
    }),
    getters: {
        zub(state) {
            this.$store.commit('SET_PROPERTY', {key: 'zub', value: value})
            this.zub = 'new value';
        }
    },
    mutations: {
        SET_PROPERTY(state, payload) {
            state[payload.key] = payload.value
        },
        changeTypeConstruction(state) {
            if (state.optionsTypeConstruction.length > 1 ) {
                state[`tooth${this.toothId}`].typeConstruction = state.optionsTypeConstruction
            }
        },

    },
    actions: {

    },
    namespaced: true,
}