export const moduleFirst = {
    state: () => ({
        teeth: [
            {toothNumber: '18',
            sortOrder: 1,
            toothState:'third-column__item',
            copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '17',
                sortOrder: 2,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '16',
                sortOrder: 3,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '15',
                sortOrder: 4,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '14',
                sortOrder: 5,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '13',
                sortOrder: 6,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '12',
                sortOrder: 7,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '11',
                sortOrder: 8,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '21',
                sortOrder: 9,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '22',
                sortOrder: 10,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '23',
                sortOrder: 11,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    colorVita: '-',
                    material: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '24',
                sortOrder: 12,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '25',
                sortOrder: 13,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '26',
                sortOrder: 14,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '27',
                sortOrder: 15,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '28',
                sortOrder: 16,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '48',
                sortOrder: 32,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '47',
                sortOrder: 31,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '46',
                sortOrder: 30,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '45',
                sortOrder: 29,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '44',
                sortOrder: 28,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '43',
                sortOrder: 27,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '42',
                sortOrder: 26,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '41',
                sortOrder: 25,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '31',
                sortOrder: 24,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '32',
                sortOrder: 23,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '33',
                sortOrder: 22,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '34',
                sortOrder: 21,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '35',
                sortOrder: 20,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '36',
                sortOrder: 19,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '37',
                sortOrder: 18,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
            {toothNumber: '38',
                sortOrder: 17,
                toothState:'third-column__item',
                copyState: false,
                stage1:{
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                },
                stage2:{
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    colorVita: '-',
                    gumPart: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    indentOptions: '-', // Убрать из текущего заказ наряда
                    selectDefault: 'Выберите значение',
                }
            },
        ],
        teeth1: [
            {toothId: 'tooth18',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '18',
                        typeConstruction: "-",
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-', // Убрать из текущего заказ наряда
                        selectDefault: 'Выберите значение',

                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '18',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth17',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '17',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '17',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth16',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '16',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '16',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth15',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '15',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '15',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth14',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '14',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '14',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth13',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '13',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '13',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth12',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '12',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '12',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth11',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '11',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '11',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth21',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '21',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '21',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth22',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '22',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '22',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth23',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '23',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '23',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth24',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '24',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '24',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth25',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '25',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '25',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth26',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '26',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '26',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth27',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '27',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '27',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth28',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '28',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                    stage2: {
                        stageNumber: '2',
                        toothNumber: '28',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
        ],
        teeth2: [
            {toothId: 'tooth38',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '38',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                    stage2: {
                        stageNumber: '2',
                        toothNumber: '38',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth37',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '37',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '37',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth36',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '36',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '36',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth35',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '35',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '35',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth34',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '34',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '34',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth33',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '33',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '33',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth32',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '32',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '32',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth31',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '31',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '31',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth41',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '41',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '41',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth42',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '42',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '42',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth43',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '43',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '43',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth44',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '44',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '44',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth45',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '45',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '45',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth46',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '46',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '46',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth47',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '47',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '47',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
            {toothId: 'tooth48',
            toothState:'third-column__item',
            copyState: false,
                stage1: {
                        stageNumber: '1',
                        toothNumber: '48',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    },
                stage2: {
                        stageNumber: '2',
                        toothNumber: '48',
                        typeConstruction: '-',
                        implantSystem: '-',
                        material: '-',
                        colorVita: '-',
                        gumPart: '-',
                        carving: 'Нет',
                        opac: 'Нет',
                        indentOptions: '-',
                        selectDefault: 'Выберите значение',
                        isFilledTooth: false,
                    }
                },
        ],

        chooseTeeth: [
            {
                'stageNumber':'-',
                "toothNumber":'-',
                "typeConstruction":'-',
                "implantSystem":'-',
                "material":'-',
                "colorVita":'-',
                "gumPart":'-',
                "carving":'-',
                "opac":'-',
            },
        ],

        newChooseTeeth: [
            {
                toothNumber: '-',
                sortOrder: 1,
                stage1: {
                    stageNumber: '1',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    gumPart: '-',
                    colorVita: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    selectDefault: 'Выберите значение',
                },
                stage2: {
                    stageNumber: '2',
                    typeConstruction: "-",
                    implantSystem: '-',
                    material: '-',
                    gumPart: '-',
                    colorVita: '-',
                    carving: 'Нет',
                    opac: 'Нет',
                    selectDefault: 'Выберите значение',
                }
            }
        ],



        optionsTypeConstruction: {
            Type1: {
                typeNameDefault: 'Анатомическая коронка',
                option1: {
                    titleTypeName: 'Анатомическая коронка',
                    chooseTypeName: 'Полная анатомия'
                },
                option2: {
                    titleTypeName: 'Анатомическая коронка',
                    chooseTypeName: 'С вестибулярным редуцированием',
                },
            },
            Type2: {
                typeNameDefault: 'Анатомическая коронка винтовой фиксации',
                option1: {
                    titleTypeName: 'Анатомическая коронка винтовой фиксации',
                    chooseTypeName: 'Полная анатомия'
                },
                option2: {
                    titleTypeName: 'Анатомическая коронка винтовой фиксации',
                    chooseTypeName: 'С вестибулярным редуцированием',
                },
            },
            Type3: {
                typeNameDefault: 'Каркас',
                option1: 'Выбран каркас',
            },
            Type4: {
                typeNameDefault: 'Каркас под нанесение',
                option1: 'Винтовой фиксации',
                option2: 'Цементной фиксации',
            },
            Type5: {
                typeNameDefault: 'Абатмент',
                option1: 'С использованием стандартных оснований',
                option2: 'С анодированием титанового абатмента',
                option3: 'С использованием жёлтых оснований',
            },
            Type6: {
                typeNameDefault: 'Вкладка',
                option1: 'Не разборная',
                option2: 'Разборная',
            },
            Type7: {
                typeNameDefault: 'Рельсовая балка',
                option1: 'С замками',
                option2: 'Под варку (с пинами)',
                option3: 'Под циркониевый мост',
            },
            Type8: {
                typeNameDefault: 'Культя',
                option1: 'Культя',
                option2: 'Культя винтовой фиксации',
            },
            Type9: {
                typeNameDefault: 'Хирургический шаблон',
                option1: 'Выбран хирургический шаблон',
            },
            Type10: {
                typeNameDefault: 'Сплинт',
                option1: 'Декомпрессионные (разгрузочные)',
                option2: 'Релаксационные (расслабляющие)',
                option3: 'Позиционирующие',
                option4: 'Стабилизирующие',
                option5: 'Репонирующие',
                option6: 'Ретенционные',
            },
            SelectOption1: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption2: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption3: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption4: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption5: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption6: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption7: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption8: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption9: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
            SelectOption10: {
                chooseTypeName: '',
                selectDefault: "Выберите значение",
                titleTypeName:'',
            },
        }
    }),
    getters: {

    },
    mutations: {
        SET_PROPERTY(state, payload) {
            state[payload.key] = payload.value
        },
        changeTypeConstruction(state) {
            if (state.optionsTypeConstruction.length > 1 ) {
                state[`tooth${this.toothId}`].typeConstruction = state.optionsTypeConstruction
            }
        },

    },
    actions: {

    },
    namespaced: true,
}