export const moduleFirst = {
    state: () => ({
        tooth18: {
            stage1: {
                stageNumber: '1',
                toothNumber: '18',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '18',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth17: {
            stage1: {
                stageNumber: '1',
                toothNumber: '17',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '17',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth16: {
            stage1: {
                stageNumber: '1',
                toothNumber: '16',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '16',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth15: {
            stage1: {
                stageNumber: '1',
                toothNumber: '15',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '15',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth14: {
            stage1: {
                stageNumber: '1',
                toothNumber: '14',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '14',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth13: {
            stage1: {
                stageNumber: '1',
                toothNumber: '13',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '13',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth12: {
            stage1: {
                stageNumber: '1',
                toothNumber: '12',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '12',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth11: {
            stage1: {
                stageNumber: '1',
                toothNumber: '11',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '11',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth21: {
            stage1: {
                stageNumber: '1',
                toothNumber: '21',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '21',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth22: {
            stage1: {
                stageNumber: '1',
                toothNumber: '22',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '22',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth23: {
            stage1: {
                stageNumber: '1',
                toothNumber: '23',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '23',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth24: {
            stage1: {
                stageNumber: '1',
                toothNumber: '24',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '24',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth25: {
            stage1: {
                stageNumber: '1',
                toothNumber: '25',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '25',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth26: {
            stage1: {
                stageNumber: '1',
                toothNumber: '26',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '26',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth27: {
            stage1: {
                stageNumber: '1',
                toothNumber: '27',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '27',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth28: {
            stage1: {
                stageNumber: '1',
                toothNumber: '28',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '28',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth48: {
            stage1: {
                stageNumber: '1',
                toothNumber: '48',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '48',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth47: {
            stage1: {
                stageNumber: '1',
                toothNumber: '47',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '47',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth46: {
            stage1: {
                stageNumber: '1',
                toothNumber: '46',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '46',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth45: {
            stage1: {
                stageNumber: '1',
                toothNumber: '45',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '45',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth44: {
            stage1: {
                stageNumber: '1',
                toothNumber: '44',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '44',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth43: {
            stage1: {
                stageNumber: '1',
                toothNumber: '43',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '43',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth42: {
            stage1: {
                stageNumber: '1',
                toothNumber: '42',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '42',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth41: {
            stage1: {
                stageNumber: '1',
                toothNumber: '41',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '41',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth31: {
            stage1: {
                stageNumber: '1',
                toothNumber: '31',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '31',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth32: {
            stage1: {
                stageNumber: '1',
                toothNumber: '32',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '32',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth33: {
            stage1: {
                stageNumber: '1',
                toothNumber: '33',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '33',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth34: {
            stage1: {
                stageNumber: '1',
                toothNumber: '34',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '34',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth35: {
            stage1: {
                stageNumber: '1',
                toothNumber: '35',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '35',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth36: {
            stage1: {
                stageNumber: '1',
                toothNumber: '36',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '36',
                typeConstruction: '',
                implantSystem: '',
                material: '',
                colorVita: '',
                gumPart: '',
                carving: '',
                indentOptions: '',
            }
        },
        tooth37: {
            stage1: {
                stageNumber: '1',
                toothNumber: '37',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '37',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        tooth38: {
            stage1: {
                stageNumber: '1',
                toothNumber: '38',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            },
            stage2: {
                stageNumber: '2',
                toothNumber: '38',
                typeConstruction: '-',
                implantSystem: '-',
                material: '-',
                colorVita: '-',
                gumPart: '-',
                carving: '-',
                indentOptions: '-',
            }
        },
        optionsTypeConstruction: {
            Type1: {
                typeNameDefault: 'Анатомическая коронка',
                option1: 'Полная анатомия',
                option2:'С вестибулярным редуцированием',
            },
            Type2: {
                typeNameDefault: 'Анатомическая коронка винтовой фиксации',
                option1: 'Полная анатомия',
                option2:'С вестибулярным редуцированием',
            },
            Type3: {
                typeNameDefault: 'Каркас',
                option1: 'Выбран каркас',
            },
            Type4: {
                typeNameDefault: 'Каркас под нанесение',
                option1: 'Винтовой фиксации',
                option2: 'Цементной фиксации',
            },
            Type5: {
                typeNameDefault: 'Абатмент',
                option1: 'С использованием стандартных оснований',
                option2: 'С анодированием титанового абатмента',
                option3: 'С использованием жёлтых оснований',
            },
            Type6: {
                typeNameDefault: 'Вкладка',
                option1: 'Не разборная',
                option2: 'Разборная',
            },
            Type7: {
                typeNameDefault: 'Рельсовая балка',
                option1: 'С замками',
                option2: 'Под варку (с пинами)',
                option3: 'Под циркониевый мост',
            },
            Type8: {
                typeNameDefault: 'Культя',
                option1: 'Культя',
                option2: 'Культя винтовой фиксации',
            },
            Type9: {
                typeNameDefault: 'Хирургический шаблон',
                option1: 'Выбран хирургический шаблон',
            },
            Type10: {
                typeNameDefault: 'Сплинт',
                option1: 'Декомпрессионные (разгрузочные)',
                option2: 'Релаксационные (расслабляющие)',
                option3: 'Позиционирующие',
                option4: 'Стабилизирующие',
                option5: 'Репонирующие',
                option6: 'Ретенционные',
            },
        }
    }),
    getters: {

    },
    mutations: {
        changeTypeConstruction(state) {
        }
    },
    actions: {

    },
    namespaced: true,
}