
const state = {
     tooth1: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '18',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '18',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth2: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '17',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '17',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth3: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '16',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '16',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth4: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '15',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '15',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth5: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '14',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '14',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth6: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '13',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '13',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth7: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '12',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '12',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth8: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '11',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '11',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth9: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '21',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '21',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth10: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '22',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '22',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth11: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '23',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '23',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth12: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '24',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '24',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth13: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '25',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '25',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth14: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '26',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '26',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth15: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '27',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '27',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth16: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '28',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '28',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth17: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '48',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '48',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth18: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '47',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '47',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth19: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '46',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '46',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth20: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '45',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '45',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth21: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '44',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '44',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth22: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '43',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '43',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth23: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '42',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '42',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth24: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '41',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '41',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth25: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '31',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '31',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth26: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '32',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '32',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth27: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '33',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '33',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth28: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '34',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '34',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth29: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '35',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '35',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth30: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '36',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '36',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth31: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '37',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '37',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
     tooth32: {
         stage1: {
             stageNumber: '1',
                 toothNumber: '38',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         },
         stage2: {
             stageNumber: '2',
                 toothNumber: '38',
                 typeConstruction: '',
                 implantSystem: '',
                 material: '',
                 colorVita: '',
                 gumPart: '',
                 carving: '',
                 indentOptions: '',
         }
     },
 }

const actions =  {

}

export default {
     namespaced: true,
     state,
     actions,
 }